### ISSUE TITLE
does not seem to work for me with svg's using raw-loader

### ISSUE THREAD

**Issue by svnm** [tomekwi/isomorphic-ensure#5]
Thanks for your work on this library by the way, it looks exactly what I need.

I am trying to run tests on some react components using tape and enzyme. However a lot of my components have inline svg's using raw loader. So to test them I need to ignore the svg's loading as it gives the following error: `Cannot find module '!raw!../assets/images/logo.svg`

I mentioned this problem I am having [here](https://stackoverflow.com/questions/36856221/how-to-ignore-raw-loader-for-testing-webpack) too. 

Here is my configuration of isomorphic-ensure

``` js
require('isomorphic-ensure')({
  loaders: {
    raw: require('raw-loader')
  },
  dirname: __dirname
})
```

**Comment by tomek-he-him** [comment]
Hi, I’m glad you like the library!

Looking at your question at StackOverflow, you’re importing your files synchronously – in the “main thread”. Unfortunately, I didn’t find a reliable way to wrap Node’s native `require` function. That’s why isomorphic-ensure only works with files loaded asynchronously via `require.ensure`.

I. e.:

``` js
if (typeof require.ensure !== 'function') {
  require.ensure = require('isomorphic-ensure')({
    loaders: {
      raw: require('raw-loader'),
    },
    dirname: __dirname,
  });
}

require.ensure(['raw!../assets/images/logo.svg'], (require) => {
  const svg = require('raw!../assets/images/logo.svg')
  …
});
```

I hope this answers your question – if it does, feel free to close the issue.

**Comment by tomek-he-him** [comment]
By the way, here’s an earlier project of mine – perhaps that could help? https://github.com/tomekwi/node-raw. The docs aren’t very good, but a look at the [test](https://github.com/tomekwi/node-raw/blob/master/test.js) should put you on track.

I don’t maintain it anymore – but if it works for you, I’ll be glad to transfer!

**Comment by svnm** [comment]
Thanks for the advice. [node-raw](https://github.com/tomekwi/node-raw) might give me what I want and hopefully I can help extend it into something that works similar to css-modules-require-hook but for svgs loaded with raw-loader.
I will close now and open any issues I have in node-raw
