### ISSUE TITLE
How does it compare to fake-file-loader & fake-url-loader?

### ISSUE THREAD

**Issue by tarikjn** [tomekwi/isomorphic-ensure#6]
Hey there,

Just found about `isomorphic-ensure`, but I am confused about its use case or what it does exactly, the documentation isn't clear and the only way I'd know is by studying the source code or running tests.

Do json-loader and raw-loader not work on the server side? If they do, how does it change the behavior?

Does it copies files for file/url loaders? How does it behave with loaders other than raw and json loaders?

Most isomorphic apps have a separate webpack client and server config with a common part, what is the advantage of using require.ensure compared to different configuration entry points? Would a build that processes server code through webpack even need this? My guess is it wouldn't as the loaded content would be part of the bundle, and this should probably be made obvious on the doc.

This also should make it clear that require.ensure is a webpack feature.

**Comment by tomek-he-him** [comment]
Hi, thanks for reaching out! As for your questions,

> Do json-loader and raw-loader not work on the server side?

They work only if you process your server code with webpack. isomorphic-ensure works in raw JS code run directly in node. It passes a custom `require` function to your callback – and that function works with loaders.

> How does it behave with loaders other than raw and json loaders?

Though I haven’t tested it with other loaders, we support the whole loader API. Any webpack loader should work.

> Does it copies files for file/url loaders?

It does exactly the same as webpack does.

> Would a build that processes server code through webpack even need this?

Nope 😃. But sometimes that’s unnecessary overhead. I wrote this module to be able to test my UI in node. I wanted my test to be fast, so building native server code with webpack would be too slow and too complex for me.

> This also should make it clear that require.ensure is a webpack feature.

Actually, it’s [in the CommonJS spec](http://wiki.commonjs.org/wiki/Modules/Async/A), but node chose not to support it.

**Comment by tarikjn** [comment]
Thanks for your detailed response, it makes a lot more sense now. So this compares more to [webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools)? Saw you updated the README with a FAQ as well, that's great, thanks :)

Here is the one thing I still find confusing, the spec define require.ensure as just being a method of loading modules once their dependencies are available, but this project also implement interoperability with webpack loaders and loader syntax (`!`), unless this is also a standard that I missed?

Also, one difference would be that instead of simply using `require`, one has to use `require.ensure`, which seems usually reserved for code splitting on the user facing parts of Webpack, am I correct? Does this module actually does anything as far as ensure that the modules and their dependencies are available?

**Comment by tomek-he-him** [comment]
Hi, glad it helped! :smiley:

> So this compares more to webpack-isomorphic-tools?

I’ve never used that, so I’m not sure. I see in the readme that webpack-isomorphic-tools compares to `target: 'node'` in webpack, which probably means that a build step is required anyway. isomorphic-ensure is definitely way simpler. It doesn’t require a build step which makes it more straightforward to use, but it probably covers way less use cases than its bigger brothers.

> this project also implement interoperability with webpack loaders and loader syntax (!), unless this is also a standard that I missed?

Nope, as far as I know this is only a feature of webpack. Getting webpack loaders to work in node without a build step was one of the main reasons I made this module.

> Does this module actually does anything as far as ensure that the modules and their dependencies are available?

Nope, it only uses the same API and calls the inner code asynchronously – just like the browser would.
